server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/storage_db
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

platform:
  observability:
    tracing:
      enabled: true
      sampling-rate: 0.1
    metrics:
      enabled: true
    logging:
      format: json
      level: INFO

# Storage configuration
storage:
  provider: ${STORAGE_PROVIDER:local}
  local:
    base-path: ${STORAGE_LOCAL_PATH:/tmp/storage}
  s3:
    bucket: ${S3_BUCKET:}
    region: ${S3_REGION:us-east-1}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
